### ISSUE TITLE
Ethornell extraction doesn't do DSC decompression after BSE decryption

### ISSUE THREAD

**Issue by arcusmaximus** [lioncash/ExtractData#5]
In e.g. Ao No Kanata No Four Rhythm, the scenario files are both compressed and encrypted, but ExtractData currently only handles the decryption. Fixing this is quite simple - see attached patch file.
[patch.txt](https://github.com/lioncash/ExtractData/files/1935398/patch.txt)

**Comment by lioncash** [comment]
Applied in 06094bd5e51637fe9f305c167b4c612649f48929. Thanks!
